### ISSUE TITLE
Error crashing the server

### ISSUE THREAD

**Issue by Nick7263** [AzureDoom/AzureDoom-Doom-Mod#17]
[WARNING] .... [minecraft/ServerWorld]: Trying to add entity with duplicated UUID c2777a33-1a5b-40fa-9ec8-9b1502c5ec8c. Existing doomweapon:rocket_mob#690, new: doomweapon:rocket_mob#690

[WARNING] .... [minecraft/ServerWorld]: Trying to add entity with duplicated UUID 032615c3-7d56-404a-a39d-4a5cb71b6c69. Existing doomweapon:rocket_mob#730, new: doomweapon:rocket_mob#730

[WARNING] .... [minecraft/ServerWorld]: Trying to add entity with duplicated UUID bb4b15b9-393b-48e8-a3c6-ddda09b435b9. Existing doomweapon:rocket_mob#747, new: doomweapon:rocket_mob#747

[WARNING] .... [minecraft/ServerWorld]: Trying to add entity with duplicated UUID adc175d0-2692-4e37-a04c-2e05394acb89. Existing doomweapon:rocket_mob#758, new: doomweapon:rocket_mob#758

[WARNING] .... [minecraft/ServerWorld]: Trying to add entity with duplicated UUID 3d7d5cc4-1ff0-4bae-8b7a-74ba13063490. Existing doomweapon:rocket_mob#780, new: doomweapon:rocket_mob#780

.... [Server thread/FATAL] [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER

.... [Server thread/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID 85beff0a-af4c-4eae-b065-dd39b56230b3

[ERROR] .... [minecraft/MinecraftServer]: Encountered an unexpected exception

net.minecraft.crash.ReportedException: Ticking entity

**Comment by Nick7263** [comment]
Forge 1.16.3

**Comment by AzureDoom** [comment]
Full crash log

**Comment by Nick7263** [comment]
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 11/21/20 5:29 PM
Description: Ticking entity

java.lang.RuntimeException: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71) ~[forge-1.16.3-34.1.42.jar:34.1] {}
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:119) ~[modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.6.jar:?] {re:classloading}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.6.jar:?] {re:classloading}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212] {}
	at software.bernie.geckolib.util.AnimationUtils.getRenderer(AnimationUtils.java:87) ~[geckolib:2.1.2] {re:classloading}
	at software.bernie.geckolib.util.AnimationUtils.getModelForEntity(AnimationUtils.java:96) ~[geckolib:2.1.2] {re:classloading}
	at software.bernie.geckolib.animation.controller.EntityAnimationController.setAnimation(EntityAnimationController.java:62) ~[geckolib:2.1.2] {re:classloading}
	at mod.azure.doom.entity.PinkyEntity.func_70609_aI(PinkyEntity.java:78) ~[doomweapon:3.3.1] {re:classloading}
	at net.minecraft.entity.LivingEntity.func_70030_z(LivingEntity.java:365) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:assets/shetiphiancore/shetiphiancore.mixins.json:MixinLivingEntity,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.MobEntity.func_70030_z(MobEntity.java:233) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.entity.Entity.func_70071_h_(Entity.java:387) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:assets/shetiphiancore/shetiphiancore.mixins.json:MixinEntity,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2113) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:assets/shetiphiancore/shetiphiancore.mixins.json:MixinLivingEntity,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:300) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:606) ~[?:?] {re:classloading,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A}
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:399) ~[?:?] {re:classloading,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:847) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercaves.mixins.json:MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:283) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:783) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercaves.mixins.json:MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:638) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercaves.mixins.json:MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:229) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercaves.mixins.json:MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71) ~[forge-1.16.3-34.1.42.jar:34.1] {}
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:119) ~[modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.6.jar:?] {re:classloading}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.6.jar:?] {re:classloading}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212] {}
	at software.bernie.geckolib.util.AnimationUtils.getRenderer(AnimationUtils.java:87) ~[geckolib:2.1.2] {re:classloading}
	at software.bernie.geckolib.util.AnimationUtils.getModelForEntity(AnimationUtils.java:96) ~[geckolib:2.1.2] {re:classloading}
	at software.bernie.geckolib.animation.controller.EntityAnimationController.setAnimation(EntityAnimationController.java:62) ~[geckolib:2.1.2] {re:classloading}
	at mod.azure.doom.entity.PinkyEntity.func_70609_aI(PinkyEntity.java:78) ~[doomweapon:3.3.1] {re:classloading}
	at net.minecraft.entity.LivingEntity.func_70030_z(LivingEntity.java:365) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:assets/shetiphiancore/shetiphiancore.mixins.json:MixinLivingEntity,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.MobEntity.func_70030_z(MobEntity.java:233) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.entity.Entity.func_70071_h_(Entity.java:387) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:assets/shetiphiancore/shetiphiancore.mixins.json:MixinEntity,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2113) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:assets/shetiphiancore/shetiphiancore.mixins.json:MixinLivingEntity,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:300) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:606) ~[?:?] {re:classloading,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A}
-- Entity being ticked --
Details:
	Entity Type: doomweapon:pinky (mod.azure.doom.entity.PinkyEntity)
	Entity ID: 6879
	Entity Name: Pinky
	Entity's Exact location: -23.92, 75.00, -4.06
	Entity's Block location: World: (-24,75,-5), Chunk: (at 8,4,11 in -2,-1; contains blocks -32,0,-16 to -17,255,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:399) ~[?:?] {re:classloading,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A}


-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['Matariel'/706, l='ServerLevel[NewWorld]', x=-21.08, y=75.00, z=-4.03]]
	Chunk stats: ServerChunkCache: 1681
	Level dimension: minecraft:the_nether
	Derived: true
	Level spawn location: World: (112,80,80), Chunk: (at 0,5,0 in 7,5; contains blocks 112,0,80 to 127,255,95), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 318252 game time, 318252 day time
	Level name: NewWorld
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 3316 (now: true), thunder time: 122661 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:847) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercaves.mixins.json:MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:283) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:783) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercaves.mixins.json:MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:638) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercaves.mixins.json:MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:229) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercaves.mixins.json:MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212] {}


-- System Details --
Details:
	Minecraft Version: 1.16.3
	Minecraft Version ID: 1.16.3
	Operating System: Linux (amd64) version 4.15.0-106-generic
	Java Version: 1.8.0_212, AdoptOpenJDK
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), AdoptOpenJDK
	Memory: 706363808 bytes (673 MB) / 2160066560 bytes (2060 MB) up to 2863661056 bytes (2731 MB)
	CPUs: 3
	JVM Flags: 6 total; -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=2 -Xms1024M -Xmx3072M -XX:-UsePerfData
	ModLauncher: 8.0.6+85+master.325de55
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-3.0.3-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.3-34.1.42.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.3-34.1.42.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.3-34.1.42.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.3-34.1.42.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.3-34.1.42.jar fml TRANSFORMATIONSERVICE 
	FML: 34.1
	Forge: net.minecraftforge:34.1.42
	FML Language Providers: 
		javafml@34.1
		minecraft@1
	Mod List: 
		forge-1.16.3-34.1.42-server.jar                   |Minecraft                     |minecraft                     |1.16.3              |DONE      |NOSIGNATURE
		useful_backpacks-1.16.3-1.11.6.83.jar             |Useful Backpacks              |usefulbackpacks               |1.11.6.83           |DONE      |f4:a6:0b:ee:cb:8a:1a:ea:9f:9d:45:91:8f:8b:b3:ae:26:f3:bf:05:86:1d:90:9e:f6:32:2a:1a:ed:1d:ce:b0
		Dungeons-Mod-1.16.3.jar                           |Dungeons Mod                  |dungeonsmod                   |1.16.3-1.0.15       |DONE      |NOSIGNATURE
		GokiStats_1.16.3_1.2.12.jar                       |Goki Stats                    |gokistats                     |1.2.12              |DONE      |NOSIGNATURE
		SilentLib-1.16.43-4.9.0+63.jar                    |Silent Lib                    |silentlib                     |4.9.0+63            |DONE      |NOSIGNATURE
		BiomesOPlenty_1.16.3_12.0.0.416_universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.16.3-12.0.0.416   |DONE      |NOSIGNATURE
		Wyrmroost-1.16.3-1.2.7.jar                        |Wyrmroost                     |wyrmroost                     |1.16.3-1.2.7        |DONE      |NOSIGNATURE
		ironfurnaces-1.16.3-2.4.0.jar                     |Iron Furnaces                 |ironfurnaces                  |2.4.0               |DONE      |NOSIGNATURE
		forge-1.16.3-geckolib-2.1.2.jar                   |GeckoLib                      |geckolib                      |2.1.2               |DONE      |NOSIGNATURE
		SilentGear-1.16.43-2.3.6+171.jar                  |Silent Gear                   |silentgear                    |2.3.6+171           |DONE      |NOSIGNATURE
		jei-1.16.3-7.6.0.45.jar                           |Just Enough Items             |jei                           |7.5.0.43            |DONE      |NOSIGNATURE
		forbidden_arcanus_1.16.3_1.0.2.jar                |Forbidden & Arcanus           |forbidden_arcanus             |1.16.3-1.0.2        |DONE      |NOSIGNATURE
		towers_of_the_wild_1.16.3_2.0.0.jar               |Towers Of The Wild            |towers_of_the_wild            |1.16.3-2.0.0        |DONE      |NOSIGNATURE
		AzureDooms-Doom-Mod-1.16.3-3.3.1.jar              |Azuredooms Doom Mod           |doomweapon                    |3.3.1               |DONE      |NOSIGNATURE
		reap-1.16.3-1.0.2.jar                             |Reap Mod                      |reap                          |1.16.3-1.0.2        |DONE      |NOSIGNATURE
		randomenchants-4.0.3.jar                          |Random Enchants               |randomenchants                |4.0.3               |DONE      |NOSIGNATURE
		curios_forge_1.16.3_4.0.2.0.jar                   |Curios API                    |curios                        |1.16.3-4.0.2.0      |DONE      |NOSIGNATURE
		Patchouli_1.16.42_47.jar                          |Patchouli                     |patchouli                     |1.16.2-47           |DONE      |NOSIGNATURE
		BetterCaves-1.16.2-1.0.4.jar                      |YUNG's Better Caves           |bettercaves                   |1.16.2-1.0.4        |DONE      |NOSIGNATURE
		leap-1.16.3-1.0.1.jar                             |Leap                          |leap                          |1.0.1               |DONE      |NOSIGNATURE
		dungeoncrawl-1.16.3-2.1.1.jar                     |Dungeon Crawl                 |dungeoncrawl                  |2.1.1               |DONE      |NOSIGNATURE
		MutantBeasts_1.16.3_1.1.2.jar                     |Mutant Beasts                 |mutantbeasts                  |1.16.3-1.1.2        |DONE      |d9:be:bd:b6:9a:e4:14:aa:05:67:fb:84:06:77:a0:c5:10:ec:27:15:1b:d6:c0:88:49:9a:ef:26:77:61:0b:5e
		guncus-1.16.2-1.3.jar                             |Gun Customization             |guncus                        |1.16.2-1.3          |DONE      |NOSIGNATURE
		EnigmaticLegacy-2.9.0.jar                         |Enigmatic Legacy              |enigmaticlegacy               |2.9.0               |DONE      |NOSIGNATURE
		toolleveling_1.16.2_1.1.0.jar                     |Tool Leveling                 |toolleveling                  |1.16.2 - 1.1.0      |DONE      |NOSIGNATURE
		u_team_core-1.16.3-3.1.10.183.jar                 |U Team Core                   |uteamcore                     |3.1.10.183          |DONE      |f4:a6:0b:ee:cb:8a:1a:ea:9f:9d:45:91:8f:8b:b3:ae:26:f3:bf:05:86:1d:90:9e:f6:32:2a:1a:ed:1d:ce:b0
		outvoted-1.16.3-b0.3.0.jar                        |Outvoted                      |outvoted                      |1.16.3-0.3.0        |DONE      |NOSIGNATURE
		forge-1.16.3-34.1.42-universal.jar                |Forge                         |forge                         |34.1.42             |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		terraqueous_1.16.3_1.7.5.jar                      |Terraqueous                   |terraqueous                   |1.7.5               |DONE      |NOSIGNATURE
		shetiphiancore-1.16-3.8.3.jar                     |ShetiPhian-Core               |shetiphiancore                |3.8.3               |DONE      |NOSIGNATURE
		fortune_gives_experience_1.16.2_1.0.0.jar         |Fortune Gives Experience      |fortune-gives-experience      |version             |DONE      |NOSIGNATURE
		BetterMineshaftsForge-1.16.2-1.0.1.jar            |YUNG's Better Mineshafts      |bettermineshafts              |1.16.2-1.0.1        |DONE      |NOSIGNATURE
		Vanilla+-Tools-Mod-1.16.3.jar                     |Vanilla+ Tools                |supertools                    |version             |DONE      |NOSIGNATURE
		ironchest-1.16.4-11.2.10.jar                      |Iron Chests                   |ironchest                     |1.16.4-11.2.10      |DONE      |NOSIGNATURE
		luckyore_1.0.0_1.16.3.jar                         |Lucky Ore                     |luckyore                      |1.0.0-1.16.3        |DONE      |NOSIGNATURE
	Crash Report UUID: 0c0be36b-7476-4563-bb39-31fde424bdaf
	Player Count: 2 / 5; [ServerPlayerEntity['Matariel'/706, l='ServerLevel[NewWorld]', x=-21.08, y=75.00, z=-4.03], ServerPlayerEntity['KittyCut'/2357, l='ServerLevel[NewWorld]', x=1190.42, y=91.00, z=1000.47]]
	Data Packs: vanilla, mod:usefulbackpacks, mod:dungeonsmod, mod:gokistats, mod:silentlib (incompatible), mod:biomesoplenty (incompatible), mod:wyrmroost (incompatible), mod:ironfurnaces, mod:geckolib (incompatible), mod:silentgear, mod:jei, mod:forbidden_arcanus (incompatible), mod:towers_of_the_wild, mod:doomweapon (incompatible), mod:reap, mod:randomenchants (incompatible), mod:curios, mod:patchouli (incompatible), mod:bettercaves (incompatible), mod:leap (incompatible), mod:dungeoncrawl, mod:mutantbeasts (incompatible), mod:guncus (incompatible), mod:enigmaticlegacy, mod:toolleveling (incompatible), mod:uteamcore, mod:outvoted (incompatible), mod:forge, mod:terraqueous, mod:shetiphiancore, mod:fortune-gives-experience, mod:bettermineshafts (incompatible), mod:supertools (incompatible), mod:ironchest (incompatible), mod:luckyore (incompatible)
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)

**Comment by AzureDoom** [comment]
3.3.1, you are like 9 updates out of date. Update to 3.4.5
