### ISSUE TITLE
REI Still broken after MCDoom update...

### ISSUE THREAD

**Issue by red2blue** [AzureDoom/AzureDoom-Doom-Mod#62]
io.netty.handler.codec.EncoderException: java.io.UTFDataFormatException: malformed input around byte 83
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.25) ~[?:?]
	at net.minecraft.network.PacketByteBuf.readNbt(PacketByteBuf:452) ~[?:?]
	at net.minecraft.network.PacketByteBuf.readNbt(PacketByteBuf:432) ~[?:?]
	at de.siphalor.nbtcrafting.ingredient.IngredientEntryCondition.read(IngredientEntryCondition.java:96) ~[6ab8f2d9-33c3-45f5-a6a5-6dfa899ac3a3.jar:?]
	at de.siphalor.nbtcrafting.ingredient.IngredientMultiStackEntry.read(IngredientMultiStackEntry.java:93) ~[6ab8f2d9-33c3-45f5-a6a5-6dfa899ac3a3.jar:?]
	at net.minecraft.recipe.Ingredient.handler$zoa000$fromPacket(Ingredient:688) ~[?:?]
	at net.minecraft.recipe.Ingredient.fromPacket(Ingredient) ~[?:?]
	at net.adriantodt.winged.recipe.WingcraftingRecipe$Companion$Serializer.read(WingcraftingRecipe.java:79) ~[winged-1.17.1-3.0.0.jar:?]
	at net.adriantodt.winged.recipe.WingcraftingRecipe$Companion$Serializer.read(WingcraftingRecipe.java:52) ~[winged-1.17.1-3.0.0.jar:?]
	at net.minecraft.network.packet.s2c.play.SynchronizeRecipesS2CPacket.readRecipe(SynchronizeRecipesS2CPacket:45) ~[?:?]
	at net.minecraft.network.PacketByteBuf.readCollection(PacketByteBuf:123) ~[?:?]
	at net.minecraft.network.PacketByteBuf.readList(PacketByteBuf:136) ~[?:?]
	at net.minecraft.network.packet.s2c.play.SynchronizeRecipesS2CPacket.<init>(SynchronizeRecipesS2CPacket:22) ~[?:?]
	at net.minecraft.network.packet.s2c.play.SynchronizeRecipesS2CPacket.handler$bpf000$replaceRecipesOnClient(SynchronizeRecipesS2CPacket:1050) ~[?:?]
	at net.minecraft.network.packet.s2c.play.SynchronizeRecipesS2CPacket.getRecipes(SynchronizeRecipesS2CPacket) ~[?:?]
	at net.minecraft.client.network.ClientPlayNetworkHandler.onSynchronizeRecipes(ClientPlayNetworkHandler:1240) ~[?:?]
	at net.minecraft.network.packet.s2c.play.SynchronizeRecipesS2CPacket.apply(SynchronizeRecipesS2CPacket:32) ~[?:?]
	at net.minecraft.network.packet.s2c.play.SynchronizeRecipesS2CPacket.apply(SynchronizeRecipesS2CPacket:14) ~[?:?]
	at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils:21) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:151) ~[?:?]
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:125) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:110) ~[?:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1075) ~[?:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:728) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:217) [intermediary-1.17.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
Caused by: java.io.UTFDataFormatException: malformed input around byte 83
	at java.io.DataInputStream.readUTF(DataInputStream.java:654) ~[?:?]
	at io.netty.buffer.ByteBufInputStream.readUTF(ByteBufInputStream.java:287) ~[netty-all-4.1.25.Final.jar:4.1.25.Final]
	at net.minecraft.nbt.NbtIo.read(NbtIo:105) ~[?:?]
	at net.minecraft.nbt.NbtIo.read(NbtIo:75) ~[?:?]
	at net.minecraft.network.PacketByteBuf.readNbt(PacketByteBuf:450) ~[?:?]
	... 31 more

**Comment by red2blue** [comment]
items show, recipes do not.
